package com.planker;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.Range;

@ConfigGroup("planker")
public interface PlankerConfig extends Config
{
    @ConfigItem(
        keyName = "apiUrl",
        name = "PlankRS API URL",
        description = "The HTTPS URL of the PlankRS clan API",
        position = 0
    )
    default String apiUrl()
    {
        return "https://api.plankrs.com";
    }

    @ConfigItem(
        keyName = "apiKey",
        name = "Plugin API key",
        description = "The private key generated by /plugin-register in the PlankRS Discord",
        secret = true,
        position = 1
    )
    default String apiKey()
    {
        return "";
    }

    @ConfigItem(
        keyName = "testConnection",
        name = "Check connection",
        description = "Run a connection check and show the result in the RuneLite chatbox",
        position = 2
    )
    default boolean testConnection()
    {
        return false;
    }

    @ConfigItem(
        keyName = "enableDropReporting",
        name = "Report drops",
        description = "Report qualifying NPC drops for the currently logged-in account",
        position = 3
    )
    default boolean enableDropReporting()
    {
        return true;
    }

    @ConfigItem(
        keyName = "enableLevelReporting",
        name = "Report level-ups",
        description = "Report qualifying level-up events for the currently logged-in account",
        position = 4
    )
    default boolean enableLevelReporting()
    {
        return true;
    }

    @ConfigItem(
        keyName = "enableQuestReporting",
        name = "Report quests",
        description = "Report completed quests for the currently logged-in account",
        position = 5
    )
    default boolean enableQuestReporting()
    {
        return true;
    }

    @ConfigItem(
        keyName = "enableCombatAchievementReporting",
        name = "Report combat achievements",
        description = "Report completed combat achievements for the currently logged-in account",
        position = 6
    )
    default boolean enableCombatAchievementReporting()
    {
        return true;
    }

    @ConfigItem(
        keyName = "enableCollectionLogReporting",
        name = "Report collection logs",
        description = "Report collection-log unlocks for the currently logged-in account",
        position = 7
    )
    default boolean enableCollectionLogReporting()
    {
        return true;
    }

    @ConfigItem(
        keyName = "attachItemIcons",
        name = "Attach item icons",
        description = "Include RuneLite item sprites with qualifying drop events",
        position = 8
    )
    default boolean attachItemIcons()
    {
        return true;
    }


    @ConfigItem(
        keyName = "enableClanChatRelay",
        name = "Relay clan chat",
        description = "Forward visible clan chat to the PlankRS Discord. Enabling this setting opens a confirmation explaining that messages from other clan members may be included.",
        position = 9
    )
    default boolean enableClanChatRelay()
    {
        return false;
    }

    @ConfigItem(
        keyName = "attachScreenshots",
        name = "Attach screenshots",
        description = "Attach a RuneLite screenshot to supported events. Screenshots may include chat, overlays, nearby player names, and other visible content. Disabled by default.",
        position = 10
    )
    default boolean attachScreenshots()
    {
        return false;
    }

    @ConfigItem(keyName = "screenshotDrops", name = "Screenshot drops", description = "Attach screenshots to qualifying drops when screenshot upload is enabled", position = 11)
    default boolean screenshotDrops() { return true; }

    @ConfigItem(keyName = "screenshotLevelUps", name = "Screenshot level-ups", description = "Attach screenshots to level-up events when screenshot upload is enabled", position = 12)
    default boolean screenshotLevelUps() { return true; }

    @ConfigItem(keyName = "screenshotQuests", name = "Screenshot quests", description = "Attach screenshots to quest completions when screenshot upload is enabled", position = 13)
    default boolean screenshotQuests() { return true; }

    @ConfigItem(keyName = "screenshotCollectionLogs", name = "Screenshot collection logs", description = "Attach screenshots to collection-log unlocks when screenshot upload is enabled", position = 14)
    default boolean screenshotCollectionLogs() { return true; }

    @ConfigItem(keyName = "screenshotCombatAchievements", name = "Screenshot combat achievements", description = "Attach screenshots to combat achievements when screenshot upload is enabled", position = 15)
    default boolean screenshotCombatAchievements() { return true; }

    @ConfigItem(keyName = "screenshotCooldownSeconds", name = "Screenshot cooldown", description = "Reuse one RuneLite frame for events occurring within this many seconds", position = 16)
    @Range(min = 0, max = 30)
    default int screenshotCooldownSeconds() { return 3; }
}
